name:                p2p
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/steshaw/p2p#readme
license:             BSD3
author:              Steven Shaw
maintainer:          steven@steshaw.org
copyright:           (c) 2017, Steven Shaw
category:            Example
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - distributed-process
  - distributed-process-p2p

executables:
  p2p:
    main:             Main.hs
